[package]
name = "sudoku"
version = "0.2.2"
edition = "2021"

[dependencies]
fnv = "1"
once_cell = "1"
rand = { version = "0.8", optional = true }

[features]
test = ["rand"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
